name: 'assembleRelease'

on:
  push:
  workflow_dispatch:
    inputs:
      send_to_discord:
        required: true
        default: false
        type: boolean
      publish_to_releases:
        required: true
        default: false
        type: boolean
      publish_artifact:
        required: true
        default: false
        type: boolean
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: gradle
      
      # Thanks https://proandroiddev.com/how-to-securely-build-and-sign-your-android-app-with-github-actions-ad5323452ce
      - name: Setup keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          KEYSTORE_PATH="$RUNNER_TEMP/keystore"
          mkdir "$KEYSTORE_PATH"
          echo $KEYSTORE_BASE64 | base64 --decode --ignore-garbage > "$KEYSTORE_PATH/keystore.jks"
      
      - name: Build with Gradle
        env:
          # ORG_GRADLE_JVMARGS: -Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease
        
      - name: Publish APK
        env:
          SEND_TO_DISCORD: ${{ github.event.inputs.send_to_discord }}
          PUBLISH_TO_RELEASES: ${{ github.event.inputs.publish_to_releases }}
          PUBLISH_ARTIFACT: ${{ github.event.inputs.publish_artifact }}
        run: |
          #TIMESTAMP=$(TZ='Asia/Dhaka' date +'%Y%m%d-%H%M')
          BOT_TOKEN="${{ secrets.BOT_TOKEN }}"
          SHORT_SHA="${GITHUB_SHA:0:7}"
          
          CONTENT=$(echo -e "'<@${{ secrets.USER_ID }}>'  \`$SHORT_SHA\`")
          #echo $SHORT_SHA
          
          mv "app/build/outputs/apk/release/app-release.apk" "app/build/outputs/apk/release/NewbShaderCollection_$SHORT_SHA.apk"
          #ls "app/build/outputs/apk/release"
          
          #ls -l "app/build/outputs/apk/release/NewbShaderCollection_$SHORT_SHA.apk"
          
          #echo [ -F "file=@app/build/outputs/apk/release/NewbShaderCollection_$SHORT_SHA.apk" ]
          
          if [ "$SEND_TO_DISCORD" = "true" ]; then
            curl -s -o /dev/null -X POST "https://discord.com/api/v10/channels/${{ secrets.CHANNEL_ID }}/messages" \
            -H "Authorization: Bot $BOT_TOKEN" \
            -F "file=@app/build/outputs/apk/release/NewbShaderCollection_$SHORT_SHA.apk" \
            -F "content=$CONTENT"
          fi
